import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'hi' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'nav.dashboard': 'Dashboard',
    'nav.solar': 'Solar',
    'nav.pumping': 'Pumping',
    'nav.grid': 'Grid',
    'nav.reports': 'Reports',
    'nav.about': 'About',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.status.safe': 'Solar Safe',
    'dashboard.status.caution': 'Battery Caution',
    'dashboard.status.stop': 'Stop Load',
    'dashboard.statusGuide': 'STATUS GUIDE',
    'dashboard.statusSafe': 'Solar Safe',
    'dashboard.statusCareful': 'Use Battery Carefully',
    'dashboard.statusStop': 'Stop Heavy Appliances',
    'dashboard.outages': 'Outages This Month',
    'dashboard.solarHours': 'Solar Hours Today',
    'dashboard.waterPumped': 'Water Pumped',
    'dashboard.energySaved': 'Energy Saved',
    'dashboard.village': 'Gadheshwar Village',
    'dashboard.location': 'Maharashtra',
    'dashboard.solarForecast': 'Today\'s Solar Forecast',
    'dashboard.waterTank': 'Water Tank Fill',
    'dashboard.goldenHour': 'Next Golden Hour',
    'dashboard.recentAlerts': 'Recent Alerts',
    'dashboard.startPump': 'Start Pump',
    'dashboard.todaySchedule': 'Today\'s Schedule',
    'dashboard.downloadReport': 'Download Report',
    'dashboard.statusSafe.desc': 'Optimal conditions for water pumping',
    'dashboard.statusCaution.desc': 'Limited solar power available',
    'dashboard.statusStop.desc': 'Grid reliability low, conserve battery',
    'dashboard.peakGeneration': 'Peak Generation',
    'dashboard.estimatedOutput': 'Estimated Output',
    'dashboard.weather': 'Weather',
    'dashboard.sunny': 'Sunny ☀️',
    'dashboard.generationConfidence': 'Generation Confidence',
    'dashboard.targetEvening': 'Target: 85% by evening',
    'dashboard.startingIn': 'Starting in',
    'dashboard.timeWindow': 'Time Window',
    'dashboard.recommendedAction': 'Recommended Action',
    'dashboard.pumpWater': 'Pump Water',
    'dashboard.alert.grid': 'Grid outage expected tomorrow 2:00 PM - 4:00 PM',
    'dashboard.alert.solar': 'Golden hour starting in 3 hours - prepare for pumping',
    'dashboard.alert.water': 'Water tank at 50% - schedule pumping session',
    'dashboard.alert.1hour': '1 hour ago',
    'dashboard.alert.2hours': '2 hours ago',
    'dashboard.alert.4hours': '4 hours ago',
    
    // Solar
    'solar.title': 'Solar Analysis',
    'solar.panelEfficiency': 'Panel Efficiency',
    'solar.dataSource': 'Data Source: NASA POWER API',
    'solar.lastUpdated': 'Last Updated',
    'solar.goldenHours': 'Golden Hours (Peak Generation)',
    'solar.forecast7day': '7-Day Solar Forecast',
    'solar.downloadForecast': 'Download Forecast',
    
    // Pumping
    'pumping.title': 'Water Pumping',
    'pumping.liveStatus': 'Live Pump Status',
    'pumping.running': 'Running',
    'pumping.stopped': 'Stopped',
    'pumping.voltageSolar': 'Voltage & Solar Correlation',
    'pumping.schedule': 'Today\'s Schedule',
    'pumping.manualOverride': 'Manual Override',
    'pumping.downloadSchedule': 'Download Schedule',
    
    // Grid
    'grid.title': 'Grid Analysis',
    'grid.liveStatus': 'Live Grid Status',
    'grid.voltageQuality': 'Voltage Quality',
    'grid.upcomingOutages': 'Upcoming Outages',
    'grid.monthlyReliability': 'Monthly Reliability',
    'grid.outageLog': 'Outage Log',
    'grid.alertMe': 'Alert me before next outage',
    
    // Reports
    'reports.title': 'Reports',
    'reports.dateRange': 'Date Range',
    'reports.reportType': 'Report Type',
    'reports.timeOfDay': 'Time of Day',
    'reports.generate': 'Generate Report',
    'reports.download': 'Download PDF',
    'reports.shareWhatsApp': 'Share via WhatsApp',
    'reports.history': 'Report History',
    
    // About
    'about.title': 'About Surya-Sanchay',
    'about.howItWorks': 'How It Works',
    'about.step1': 'Satellite Data',
    'about.step2': 'AI Processing',
    'about.step3': 'Schedule Generated',
    'about.faq': 'Frequently Asked Questions',
    'about.impact': 'Our Impact',
    'about.sdg7': 'SDG Goal 7: Affordable & Clean Energy',
    'about.sdg8': 'SDG Goal 8: Decent Work & Economic Growth',
    'about.contact': 'Contact Us',
    'about.poweredBy': 'Powered by Satellite Data & Community Action',
    
    // Common
    'common.liters': 'Liters',
    'common.hours': 'Hours',
    'common.minutes': 'Minutes',
    'common.am': 'AM',
    'common.pm': 'PM',
    'common.today': 'Today',
    'common.tomorrow': 'Tomorrow',
    'common.thisWeek': 'This Week',
    'common.thisMonth': 'This Month',
    'common.updatedAgo': 'Updated 2 min ago',
    
    // Grid
    'grid.subtitle': 'Monitor grid reliability and plan around outages',
    'grid.online': 'Online',
    'grid.offline': 'Offline',
    'grid.voltage': 'Voltage',
    'grid.frequency': 'Frequency',
    'grid.monthlyUptime': 'Monthly Uptime',
    'grid.outagesThisMonth': 'Outages This Month',
    'grid.stable': 'Stable',
    'grid.normal': 'Normal',
    'grid.vsLastMonth': 'vs last month',
    'grid.currentVoltage': 'Current Voltage',
    'grid.optimalRange': 'Optimal Range',
    'grid.min': 'Min',
    'grid.max': 'Max',
    'grid.optimal': 'Optimal',
    'grid.reason': 'Reason',
    'grid.area': 'Area',
    'grid.averageUptime': 'Average Uptime',
    'grid.totalOutages': 'Total Outages',
    'grid.date': 'Date',
    'grid.time': 'Time',
    'grid.duration': 'Duration',
    'grid.scheduledMaintenance': 'Scheduled Maintenance',
    'grid.lineRepair': 'Line Repair',
    'grid.transformerUpgrade': 'Transformer Upgrade',
    
    // Solar
    'solar.subtitle': 'Real-time solar analysis and forecasting',
    'solar.optimalPerformance': 'Optimal performance',
    'solar.todaysGeneration': 'Today\'s Generation',
    'solar.target': 'Target: 8.5 kWh',
    'solar.24hProfile': '24-Hour Solar Generation Profile',
    'solar.goldenHoursDesc': 'highlighted in amber (11 AM - 2 PM)',
    'solar.goldenHoursTime': 'Golden Hours: 11:00 AM - 2:00 PM',
    'solar.peakWindow': 'Peak generation window - optimal for water pumping',
    'solar.weather.sunny': 'Sunny',
    'solar.weather.cloudy': 'Cloudy',
    'solar.weather.partlyCloudy': 'Partly Cloudy',
    'solar.excellent': 'Excellent',
    'solar.good': 'Good',
    'solar.fair': 'Fair',
    'solar.panelDetails': 'Solar Panel Details',
    'solar.totalCapacity': 'Total Capacity',
    'solar.panelType': 'Panel Type',
    'solar.installDate': 'Installation Date',
    'solar.warranty': 'Warranty Period',
    'solar.monthlyPerformance': 'Monthly Performance',
    'solar.avgDaily': 'Average Daily',
    'solar.bestDay': 'Best Day',
    'solar.activePanels': 'Active Panels',
    'solar.temperature': 'Temperature',
    'solar.cloudCover': 'Cloud Cover',
    
    // Pumping
    'pumping.subtitle': 'Optimize water pumping during solar peaks',
    'pumping.currentVoltage': 'Current Voltage',
    'pumping.solarGeneration': 'Solar Generation',
    'pumping.waterFlow': 'Water Flow Rate',
    'pumping.runningDuration': 'Running Duration',
    'pumping.optimal': 'Optimal',
    'pumping.correlationDesc': 'Correlation between grid voltage and solar generation',
    'pumping.voltage': 'Voltage',
    'pumping.solar': 'Solar',
    'pumping.duration': 'Duration',
    'pumping.solarPower': 'Solar Power',
    'pumping.waterTarget': 'Water Target',
    'pumping.status.completed': 'Completed',
    'pumping.status.active': 'Active',
    'pumping.status.scheduled': 'Scheduled',
    'pumping.override.title': 'Manual Override',
    'pumping.override.desc': 'Override the automated schedule to manually control the pump. Use this feature only when necessary.',
    'pumping.override.important': 'Important Considerations:',
    'pumping.override.rule1': 'Check current solar generation before starting',
    'pumping.override.rule2': 'Ensure grid voltage is stable (220-240V)',
    'pumping.override.rule3': 'Monitor water tank levels',
    'pumping.override.rule4': 'Manual runs may affect scheduled operations',
    'pumping.override.currentCond': 'Current Conditions:',
    'pumping.override.cancel': 'Cancel',
    'pumping.override.stop': 'Stop Pump',
    'pumping.override.start': 'Start Pump',
    
    // About
    'about.subtitle': 'Empowering rural India with smart solar management for sustainable agriculture',
    'about.badge.solar': 'Solar-Powered',
    'about.badge.ai': 'AI-Driven',
    'about.badge.gov': 'Government-Grade',
    'about.howItWorksSubtitle': 'Three simple steps to optimize your solar usage',
    'about.step': 'Step',
    'about.impactSubtitle': 'Real results from Gadheshwar Village',
    'about.impact.villages': 'Villages Covered',
    'about.impact.energy': 'Energy Saved',
    'about.impact.water': 'Water Pumped',
    'about.impact.cost': 'Cost Savings',
    'about.sdgTitle': 'Contributing to UN Sustainable Development Goals',
    'about.sdg7.desc': 'By maximizing solar energy utilization and reducing grid dependency, we ensure access to affordable, reliable, sustainable, and modern energy for all.',
    'about.sdg8.desc': 'Lower operational costs and improved agricultural productivity promote sustained economic growth and enhance farmer livelihoods.',
    'about.faqSubtitle': 'Common questions about Surya-Sanchay',
    'about.contactTech': 'Technical Support',
    'about.contactAdmin': 'Administrative Office',
    'about.contactPrivacy': 'Data Privacy & Security',
    'about.contactPrivacyDesc': 'All data is stored securely and complies with Government of India data protection guidelines. We do not share personal information with third parties without explicit consent.',
    'about.btn.contact': 'Contact Support',
    'about.btn.docs': 'View Documentation',
    'about.tags.api': 'NASA POWER API',
    'about.tags.ai': 'AI/ML Processing',
    'about.tags.monitor': 'Real-time Monitoring',
    'about.tags.feedback': 'Community Feedback',
    'reports.subtitle': 'Generate and download official compliance reports',
    'reports.filterTitle': 'Filter Reports',
    'reports.previewTitle': 'Report Preview',
    'reports.graphTitle': 'Graphical Representation',
    'reports.cat.solar.title': 'Solar Performance Report',
    'reports.cat.solar.desc': 'Detailed analysis of solar panel efficiency and generation',
    'reports.cat.pumping.title': 'Water Pumping Report',
    'reports.cat.pumping.desc': 'Water usage, pumping schedule compliance, and optimization',
    'reports.cat.grid.title': 'Grid Reliability Report',
    'reports.cat.grid.desc': 'Outage patterns, voltage quality, and grid performance',
    'reports.cat.compliance.title': 'Compliance Report',
    'reports.cat.compliance.desc': 'Government scheme compliance and SDG goal tracking',
    'reports.cat.combined.title': 'Combined Report',
    'reports.cat.combined.desc': 'All-in-one report with solar, pumping, and grid data',
    'reports.period': 'Period:',
    'reports.keyMetrics': 'Key Metrics',
    'reports.metric.gen': 'Total Generation',
    'reports.metric.peak': 'Peak Power',
    'reports.metric.eff': 'Efficiency',
    'reports.metric.golden': 'Golden Hours',
    'reports.metric.water': 'Total Water Pumped',
    'reports.metric.sessions': 'Pumping Sessions',
    'reports.metric.energy': 'Energy Used',
    'reports.metric.compliance': 'Schedule Compliance',
    'reports.metric.uptime': 'Grid Uptime',
    'reports.metric.outages': 'Total Outages',
    'reports.metric.avgVolt': 'Avg Voltage',
    'reports.metric.downtime': 'Downtime Hours',
    'reports.metric.sdg7': 'SDG 7 Score',
    'reports.metric.sdg8': 'SDG 8 Score',
    'reports.metric.kusum': 'PM-KUSUM Compliance',
    'reports.metric.savings': 'Cost Savings',
    'reports.col.date': 'Date Generated',
    'reports.col.type': 'Report Type',
    'reports.col.period': 'Period',
    'reports.col.size': 'Size',
    'reports.col.status': 'Status',
    'reports.col.actions': 'Actions',
    'common.action': 'Action',
    'common.weekly': 'Weekly',
    'common.monthly': 'Monthly',
    'common.quarterly': 'Quarterly',
    'common.yearly': 'Yearly',
    'common.custom': 'Custom Date Range',
    'reports.period.weekly': 'Last 7 Days',
    'reports.period.monthly': 'Last 30 Days',
    'reports.period.quarterly': 'Last 3 Months',
    'reports.period.yearly': 'Last 12 Months',
    'reports.period.custom': 'Custom Range',
    'common.startDate': 'Start Date',
    'common.endDate': 'End Date',
    'common.lastMonth': 'Last Month',
    // Common UI
    'common.refresh': 'Refresh',
    'common.live': 'Live',
    'common.loading': 'Loading…',
    'common.noData': 'No data found',
    'common.manual': 'Manual',
    'common.updated': 'Updated',
    // Dashboard new
    'dashboard.subtitle': 'Gadheshwar Gram Panchayat · Solar Monitoring',
    'dashboard.activePanels': 'Active Panels',
    'dashboard.moneySaved': 'Money Saved',
    'dashboard.villageDesc': 'Solar-powered water pumping system',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.action.pumping': 'Pumping Sessions',
    'dashboard.action.pumpingDesc': 'View all water pumping records',
    'dashboard.action.grid': 'Grid Monitor',
    'dashboard.action.gridDesc': 'Check live grid status',
    'dashboard.action.reportDesc': 'Export solar performance PDF',
    // Grid new
    'grid.realtimeDesc': 'Real-time grid status & history',
    'grid.currentStatus': 'Current Status',
    'grid.uptime': 'Uptime',
    'grid.totalRecords': 'Total Records',
    'grid.onlineEvents': 'Online Events',
    'grid.voltageTrend': 'Voltage Trend',
    'grid.history': 'Grid History',
    'grid.status': 'Status',
    'grid.timestamp': 'Timestamp',
    'grid.noRecords': 'No grid records found',
    // Pumping new
    'pumping.totalSessions': 'Total Sessions',
    'pumping.energyUsed': 'Energy Used',
    'pumping.efficiency': 'Efficiency',
    'pumping.recentSessions': 'Recent Sessions',
    'pumping.total': 'total',
    'pumping.water': 'Water',
    'pumping.energy': 'Energy',
    'pumping.startTime': 'Start',
    'pumping.noSessions': 'No pumping sessions found',
    'pumping.override.active': 'OVERRIDE ACTIVE',
    'pumping.override.on': 'Override ON',
    'pumping.override.off': 'Override OFF',
    'pumping.override.disabled': 'Manual override is disabled',
    'pumping.override.disabledDesc': 'Enable override to manually start or stop the water pump outside of the automated schedule. Use only in emergency or maintenance situations.',
    'pumping.override.warning': 'Warning',
    'pumping.override.warningText': 'Manual override bypasses the automated solar schedule. Only use when necessary. Sessions will be logged as manual in the records.',
    'pumping.override.targetWaterLabel': 'Target Water Volume (litres) — optional',
    'pumping.override.targetWaterHint': 'Leave blank to estimate from duration',
    'pumping.override.durationLabel': 'Duration Limit (minutes) — optional',
    'pumping.override.durationHint': 'Pump will auto-stop after this time',
    'pumping.override.startNow': 'Start Pump Now',
    'pumping.override.stopSave': 'Stop Pump & Save',
    'pumping.override.saving': 'Saving session…',
    'pumping.override.pumpRunning': 'Pump Running',
    'pumping.override.estWater': 'Est. Water',
    'pumping.override.estEnergy': 'Est. Energy',
    'pumping.override.startedAt': 'Started at',
    'pumping.override.durationLimitLabel': 'Duration limit',
    // Reports new
    'reports.liveDataTitle': 'Reports pull live data from Supabase',
    'reports.liveDataDesc': 'Each PDF is generated fresh from your database. Make sure you are connected to the internet.',
    'reports.allInOne': 'All-in-one',
    'reports.generating': 'Generating…',
    'reports.downloaded': 'Downloaded!',
    'reports.footer': 'Reports are generated in PDF format. All data belongs to Gadheshwar Gram Panchayat.',
  },
  hi: {
    // Header
    'nav.dashboard': 'डैशबोर्ड',
    'nav.solar': 'सौर ऊर्जा',
    'nav.pumping': 'जल पंपिंग',
    'nav.grid': 'विद्युत ग्रिड',
    'nav.reports': 'रिपोर्ट',
    'nav.about': 'परिचय',
    
    // Dashboard
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.status.safe': 'सौर ऊर्जा सुरक्षित',
    'dashboard.status.caution': 'बैटरी सावधानी',
    'dashboard.status.stop': 'भार रोकें',
    'dashboard.statusGuide': 'स्थिति गाइड',
    'dashboard.statusSafe': 'सौर ऊर्जा सुरक्षित',
    'dashboard.statusCareful': 'बैटरी सावधानी से उपयोग करें',
    'dashboard.statusStop': 'भारी उपकरण बंद करें',
    'dashboard.outages': 'इस महीने आउटेज',
    'dashboard.solarHours': 'आज सौर घंटे',
    'dashboard.waterPumped': 'पंप किया गया पानी',
    'dashboard.energySaved': 'बचाई गई ऊर्जा',
    'dashboard.village': 'गढेश्वर गांव',
    'dashboard.location': 'महाराष्ट्र',
    'dashboard.solarForecast': 'आज का सौर पूर्वानुमान',
    'dashboard.waterTank': 'जल टैंक भरण',
    'dashboard.goldenHour': 'अगला स्वर्णिम घंटा',
    'dashboard.recentAlerts': 'हाल की सूचनाएं',
    'dashboard.startPump': 'पंप चालू करें',
    'dashboard.todaySchedule': 'आज की अनुसूची',
    'dashboard.downloadReport': 'रिपोर्ट डाउनलोड करें',
    'dashboard.statusSafe.desc': 'जल पंपिंग के लिए अनुकूल स्थितियाँ',
    'dashboard.statusCaution.desc': 'सीमित सौर ऊर्जा उपलब्ध',
    'dashboard.statusStop.desc': 'ग्रिड विश्वसनीयता कम, बैटरी बचाएं',
    'dashboard.peakGeneration': 'चरम उत्पादन',
    'dashboard.estimatedOutput': 'अनुमानित आउटपुट',
    'dashboard.weather': 'मौसम',
    'dashboard.sunny': 'धूप ☀️',
    'dashboard.generationConfidence': 'उत्पादन आत्मविश्वास',
    'dashboard.targetEvening': 'लक्ष्य: शाम तक 85%',
    'dashboard.startingIn': 'शुरू होने में',
    'dashboard.timeWindow': 'समय सीमा',
    'dashboard.recommendedAction': 'अनुशंसित कार्रवाई',
    'dashboard.pumpWater': 'पंप जल',
    'dashboard.alert.grid': 'कल दोपहर 2:00 बजे - 4:00 बजे ग्रिड आउटेज की उम्मीद',
    'dashboard.alert.solar': 'स्वर्णिम घंटा 3 घंटे में शुरू होगा - पंपिंग की तैयारी करें',
    'dashboard.alert.water': 'पानी की टंकी 50% पर - पंपिंग सत्र निर्धारित करें',
    'dashboard.alert.1hour': '1 घंटे पहले',
    'dashboard.alert.2hours': '2 घंटे पहले',
    'dashboard.alert.4hours': '4 घंटे पहले',
    
    // Solar
    'solar.title': 'सौर विश्लेषण',
    'solar.panelEfficiency': 'पैनल दक्षता',
    'solar.dataSource': 'डेटा स्रोत: NASA POWER API',
    'solar.lastUpdated': 'अंतिम अपडेट',
    'solar.goldenHours': 'स्वर्णिम घंटे (चरम उत्पादन)',
    'solar.forecast7day': '7-दिवसीय सौर पूर्वानुमान',
    'solar.downloadForecast': 'पूर्वानुमान डाउनलोड करें',
    
    // Pumping
    'pumping.title': 'जल पंपिंग',
    'pumping.liveStatus': 'लाइव पंप स्थिति',
    'pumping.running': 'चल रहा है',
    'pumping.stopped': 'रुका हुआ',
    'pumping.voltageSolar': 'वोल्टेज और सौर सहसंबंध',
    'pumping.schedule': 'आज की अनुसूची',
    'pumping.manualOverride': 'मैन्युअल नियंत्रण',
    'pumping.downloadSchedule': 'अनुसूची डाउनलोड करें',
    
    // Grid
    'grid.title': 'ग्रिड विश्लेषण',
    'grid.liveStatus': 'लाइव ग्रिड स्थिति',
    'grid.voltageQuality': 'वोल्टेज गुणवत्ता',
    'grid.upcomingOutages': 'आगामी आउटेज',
    'grid.monthlyReliability': 'मासिक विश्वसनीयता',
    'grid.outageLog': 'आउटेज लॉग',
    'grid.alertMe': 'अगले आउटेज से पहले मुझे सूचित करें',
    
    // Reports
    'reports.title': 'रिपोर्ट',
    'reports.dateRange': 'तिथि सीमा',
    'reports.reportType': 'रिपोर्ट प्रकार',
    'reports.timeOfDay': 'दिन का समय',
    'reports.generate': 'रिपोर्ट बनाएं',
    'reports.download': 'PDF डाउनलोड करें',
    'reports.shareWhatsApp': 'व्हाट्सएप द्वारा साझा करें',
    'reports.history': 'रिपोर्ट इतिहास',
    
    // About
    'about.title': 'सूर्य-संचय के बारे में',
    'about.howItWorks': 'यह कैसे काम करता है',
    'about.step1': 'उपग्रह डेटा',
    'about.step2': 'AI प्रसंस्करण',
    'about.step3': 'अनुसूची तैयार',
    'about.faq': 'अक्सर पूछे जाने वाले प्रश्न',
    'about.impact': 'हमारा प्रभाव',
    'about.sdg7': 'SDG लक्ष्य 7: किफायती और स्वच्छ ऊर्जा',
    'about.sdg8': 'SDG लक्ष्य 8: अच्छा काम और आर्थिक विकास',
    'about.contact': 'हमसे संपर्क करें',
    'about.poweredBy': 'उपग्रह डेटा और सामुदायिक कार्रवाई द्वारा संचालित',
    
    // Common
    'common.liters': 'लीटर',
    'common.hours': 'घंटे',
    'common.minutes': 'मिनट',
    'common.today': 'आज',
    'common.tomorrow': 'कल',
    'common.thisWeek': 'इस सप्ताह',
    'common.thisMonth': 'इस महीने',
    'common.updatedAgo': '2 मिनट पहले अपडेट किया गया',
    
    // Grid
    'grid.subtitle': 'ग्रिड विश्वसनीयता की निगरानी और आउटेज की योजना बनाएं',
    'grid.online': 'ऑनलाइन',
    'grid.offline': 'ऑफ़लाइन',
    'grid.voltage': 'वोल्टेज',
    'grid.frequency': 'आवृत्ति',
    'grid.monthlyUptime': 'मासिक अपटाइम',
    'grid.outagesThisMonth': 'इस महीने आउटेज',
    'grid.stable': 'स्थिर',
    'grid.normal': 'सामान्य',
    'grid.vsLastMonth': 'पिछले महीने के मुकाबले',
    'grid.currentVoltage': 'वर्तमान वोल्टेज',
    'grid.optimalRange': 'इष्टतम सीमा',
    'grid.min': 'न्यूनतम',
    'grid.max': 'अधिकतम',
    'grid.optimal': 'इष्टतम',
    'grid.reason': 'कारण',
    'grid.area': 'क्षेत्र',
    'grid.averageUptime': 'औसत अपटाइम',
    'grid.totalOutages': 'कुल आउटेज',
    'grid.date': 'तारीख',
    'grid.time': 'समय',
    'grid.duration': 'अवधि',
    'grid.scheduledMaintenance': 'निर्धारित रखरखाव',
    'grid.lineRepair': 'लाइन मरम्मत',
    'grid.transformerUpgrade': 'ट्रांसफार्मर अपग्रेड',
    
    // Solar
    'solar.subtitle': 'वास्तविक समय सौर विश्लेषण और पूर्वानुमान',
    'solar.optimalPerformance': 'इष्टतम प्रदर्शन',
    'solar.todaysGeneration': 'आज का उत्पादन',
    'solar.target': 'लक्ष्य: 8.5 kWh',
    'solar.24hProfile': '24-घंटे सौर उत्पादन प्रोफ़ाइल',
    'solar.goldenHoursDesc': 'एम्बर में हाइलाइट किया गया (11 AM - 2 PM)',
    'solar.goldenHoursTime': 'स्वर्णिम घंटे: 11:00 AM - 2:00 PM',
    'solar.peakWindow': 'पीक जनरेशन विंडो - वाटर पंपिंग के लिए इष्टतम',
    'solar.weather.sunny': 'धूप',
    'solar.weather.cloudy': 'बादल',
    'solar.weather.partlyCloudy': 'आंशिक रूप से बादल',
    'solar.excellent': 'उत्कृष्ट',
    'solar.good': 'अच्छा',
    'solar.fair': 'ठीक',
    'solar.panelDetails': 'सौर पैनल विवरण',
    'solar.totalCapacity': 'कुल क्षमता',
    'solar.panelType': 'पैनल का प्रकार',
    'solar.installDate': 'स्थापना की तारीख',
    'solar.warranty': 'वारंटी अवधि',
    'solar.monthlyPerformance': 'मासिक प्रदर्शन',
    'solar.avgDaily': 'औसत दैनिक',
    'solar.bestDay': 'सबसे अच्छा दिन',
    'solar.activePanels': 'सक्रिय पैनल',
    'solar.temperature': 'तापमान',
    'solar.cloudCover': 'बादल आवरण',
    
    // Pumping
    'pumping.subtitle': 'सौर चरम के दौरान जल पंपिंग का अनुकूलन करें',
    'pumping.currentVoltage': 'वर्तमान वोल्टेज',
    'pumping.solarGeneration': 'सौर उत्पादन',
    'pumping.waterFlow': 'जल प्रवाह दर',
    'pumping.runningDuration': 'चलने की अवधि',
    'pumping.optimal': 'इष्टतम',
    'pumping.correlationDesc': 'ग्रिड वोल्टेज और सौर उत्पादन के बीच सहसंबंध',
    'pumping.voltage': 'वोल्टेज',
    'pumping.solar': 'सौर',
    'pumping.duration': 'अवधि',
    'pumping.solarPower': 'सौर ऊर्जा',
    'pumping.waterTarget': 'जल लक्ष्य',
    'pumping.status.completed': 'पुरा होना',
    'pumping.status.active': 'सक्रिय',
    'pumping.status.scheduled': 'निर्धारित',
    'pumping.override.title': 'मैन्युअल ओवरराइड',
    'pumping.override.desc': 'पंप को मैन्युअल रूप से नियंत्रित करने के लिए स्वचालित शेड्यूलिंग को ओवरराइड करें।',
    'pumping.override.important': 'महत्वपूर्ण विचार:',
    'pumping.override.rule1': 'शुरू करने से पहले वर्तमान सौर उत्पादन की जांच करें',
    'pumping.override.rule2': 'सुनिश्चित करें कि ग्रिड वोल्टेज स्थिर है (220-240V)',
    'pumping.override.rule3': 'पानी की टंकी के स्तर की निगरानी करें',
    'pumping.override.rule4': 'मैन्युअल संचालन अनुसूचित संचालन को प्रभावित कर सकता है',
    'pumping.override.currentCond': 'वर्तमान स्थितियाँ:',
    'pumping.override.cancel': 'रद्द करें',
    'pumping.override.stop': 'पंप रोकें',
    'pumping.override.start': 'पंप शुरू करें',
    
    // About
    'about.subtitle': 'सतत कृषि के लिए स्मार्ट सौर प्रबंधन के साथ ग्रामीण भारत को सशक्त बनाना',
    'about.badge.solar': 'सौर-संचालित',
    'about.badge.ai': 'AI-संचालित',
    'about.badge.gov': 'सरकारी-ग्रेड',
    'about.howItWorksSubtitle': 'सौर उपयोग को अनुकूलित करने के तीन आसान चरण',
    'about.step': 'चरण',
    'about.impactSubtitle': 'गढेश्वर गांव के वास्तविक परिणाम',
    'about.impact.villages': 'गांव शामिल',
    'about.impact.energy': 'बचाई गई ऊर्जा',
    'about.impact.water': 'पंप किया गया पानी',
    'about.impact.cost': 'लागत की बचत',
    'about.sdgTitle': 'संयुक्त राष्ट्र सतत विकास लक्ष्यों में योगदान',
    'about.sdg7.desc': 'सौर ऊर्जा उपयोग को अधिकतम करके और ग्रिड निर्भरता को कम करके, हम सभी के लिए सस्ती, विश्वसनीय, टिकाऊ और आधुनिक ऊर्जा सुनिश्चित करते हैं।',
    'about.sdg8.desc': 'कम परिचालन लागत और उन्नत कृषि उत्पादकता सतत आर्थिक विकास को बढ़ावा देती है और किसानों की आजीविका में सुधार करती है।',
    'about.faqSubtitle': 'सूर्य-संचय के बारे में सामान्य प्रश्न',
    'about.contactTech': 'तकनीकी सहायता',
    'about.contactAdmin': 'प्रबंधन कार्यालय',
    'about.contactPrivacy': 'डेटा गोपनीयता और सुरक्षा',
    'about.contactPrivacyDesc': 'सभी डेटा सुरक्षित रूप से संग्रहीत किया जाता है और भारत सरकार के डेटा सुरक्षा दिशानिर्देशों का अनुपालन करता है।',
    'about.btn.contact': 'सहायता से संपर्क करें',
    'about.btn.docs': 'दस्तावेज़ देखें',
    'about.tags.api': 'NASA POWER API',
    'about.tags.ai': 'AI/ML प्रसंस्करण',
    'about.tags.monitor': 'रीयल-टाइम मॉनिटरिंग',
    'about.tags.feedback': 'सामुदायिक प्रतिक्रिया',
    'reports.subtitle': 'आधिकारिक अनुपालन रिपोर्ट बनाएं और डाउनलोड करें',
    'reports.filterTitle': 'रिपोर्ट फ़िल्टर करें',
    'reports.previewTitle': 'रिपोर्ट पूर्वावलोकन',
    'reports.graphTitle': 'ग्राफिकल प्रस्तुति',
    'reports.cat.solar.title': 'सौर प्रदर्शन रिपोर्ट',
    'reports.cat.solar.desc': 'सौर पैनल दक्षता और उत्पादन का विस्तृत विश्लेषण',
    'reports.cat.pumping.title': 'जल पंपिंग रिपोर्ट',
    'reports.cat.pumping.desc': 'जल उपयोग, पंपिंग अनुसूची अनुपालन, और अनुकूलन',
    'reports.cat.grid.title': 'ग्रिड विश्वसनीयता रिपोर्ट',
    'reports.cat.grid.desc': 'आउटेज पैटर्न, वोल्टेज गुणवत्ता, और ग्रिड प्रदर्शन',
    'reports.cat.compliance.title': 'अनुपालन रिपोर्ट',
    'reports.cat.compliance.desc': 'सरकारी योजना अनुपालन और SDG लक्ष्य ट्रैकिंग',
    'reports.cat.combined.title': 'संयुक्त रिपोर्ट',
    'reports.cat.combined.desc': 'सौर, पंपिंग और ग्रिड डेटा के साथ एकीकृत रिपोर्ट',
    'reports.period': 'अवधि:',
    'reports.keyMetrics': 'प्रमुख मेट्रिक्स',
    'reports.metric.gen': 'कुल उत्पादन',
    'reports.metric.peak': 'पीक पावर',
    'reports.metric.eff': 'दक्षता',
    'reports.metric.golden': 'स्वर्णिम घंटे',
    'reports.metric.water': 'कुल पंप किया गया पानी',
    'reports.metric.sessions': 'पंपिंग सत्र',
    'reports.metric.energy': 'उपयोग की गई ऊर्जा',
    'reports.metric.compliance': 'अनुसूची अनुपालन',
    'reports.metric.uptime': 'ग्रिड अपटाइम',
    'reports.metric.outages': 'कुल आउटेज',
    'reports.metric.avgVolt': 'औसत वोल्टेज',
    'reports.metric.downtime': 'डाउनटाइम घंटे',
    'reports.metric.sdg7': 'SDG 7 स्कोर',
    'reports.metric.sdg8': 'SDG 8 स्कोर',
    'reports.metric.kusum': 'PM-KUSUM अनुपालन',
    'reports.metric.savings': 'लागत बचत',
    'reports.col.date': 'उत्पन्न तिथि',
    'reports.col.type': 'रिपोर्ट प्रकार',
    'reports.col.period': 'अवधि',
    'reports.col.size': 'आकार',
    'reports.col.status': 'स्थिति',
    'reports.col.actions': 'कार्रवाई',
    'common.action': 'कार्रवाई',
    'common.weekly': 'साप्ताहिक',
    'common.monthly': 'मासिक',
    'common.quarterly': 'त्रैमासिक',
    'common.yearly': 'वार्षिक',
    'common.custom': 'कस्टम तिथि सीमा',
    'reports.period.weekly': 'पिछले 7 दिन',
    'reports.period.monthly': 'पिछले 30 दिन',
    'reports.period.quarterly': 'पिछले 3 महीने',
    'reports.period.yearly': 'पिछले 12 महीने',
    'reports.period.custom': 'कस्टम सीमा',
    'common.startDate': 'प्रारंभ तिथि',
    'common.endDate': 'समाप्ति तिथि',
    'common.lastMonth': 'पिछले महीने',
    // Common UI
    'common.refresh': 'ताज़ा करें',
    'common.live': 'लाइव',
    'common.loading': 'लोड हो रहा है…',
    'common.noData': 'कोई डेटा नहीं',
    'common.manual': 'मैन्युअल',
    'common.updated': 'अपडेट किया',
    // Dashboard new
    'dashboard.subtitle': 'गढ़ेश्वर ग्राम पंचायत · सौर निगरानी',
    'dashboard.activePanels': 'सक्रिय पैनल',
    'dashboard.moneySaved': 'पैसे बचाए',
    'dashboard.villageDesc': 'सौर ऊर्जा से जल पंपिंग',
    'dashboard.quickActions': 'त्वरित क्रियाएँ',
    'dashboard.action.pumping': 'पंपिंग सत्र',
    'dashboard.action.pumpingDesc': 'सभी जल पंपिंग रिकॉर्ड देखें',
    'dashboard.action.grid': 'ग्रिड मॉनिटर',
    'dashboard.action.gridDesc': 'लाइव ग्रिड स्थिति जांचें',
    'dashboard.action.reportDesc': 'सौर प्रदर्शन PDF निर्यात करें',
    // Grid new
    'grid.realtimeDesc': 'रीयल-टाइम ग्रिड स्थिति और इतिहास',
    'grid.currentStatus': 'वर्तमान स्थिति',
    'grid.uptime': 'अपटाइम',
    'grid.totalRecords': 'कुल रिकॉर्ड',
    'grid.onlineEvents': 'ऑनलाइन घटनाएँ',
    'grid.voltageTrend': 'वोल्टेज ट्रेंड',
    'grid.history': 'ग्रिड इतिहास',
    'grid.status': 'स्थिति',
    'grid.timestamp': 'समय',
    'grid.noRecords': 'कोई ग्रिड रिकॉर्ड नहीं',
    // Pumping new
    'pumping.totalSessions': 'कुल सत्र',
    'pumping.energyUsed': 'उपयोग की गई ऊर्जा',
    'pumping.efficiency': 'दक्षता',
    'pumping.recentSessions': 'हाल के सत्र',
    'pumping.total': 'कुल',
    'pumping.water': 'पानी',
    'pumping.energy': 'ऊर्जा',
    'pumping.startTime': 'शुरुआत',
    'pumping.noSessions': 'कोई पंपिंग सत्र नहीं',
    'pumping.override.active': 'ओवरराइड सक्रिय',
    'pumping.override.on': 'ओवरराइड चालू',
    'pumping.override.off': 'ओवरराइड बंद',
    'pumping.override.disabled': 'मैन्युअल ओवरराइड अक्षम है',
    'pumping.override.disabledDesc': 'स्वचालित शेड्यूल के बाहर पंप को मैन्युअल रूप से चालू/बंद करने के लिए ओवरराइड सक्षम करें। केवल आपातकाल में उपयोग करें।',
    'pumping.override.warning': 'चेतावनी',
    'pumping.override.warningText': 'मैन्युअल ओवरराइड स्वचालित सौर शेड्यूल को बायपास करता है। केवल आवश्यक होने पर उपयोग करें। सत्र मैन्युअल के रूप में दर्ज किए जाएंगे।',
    'pumping.override.targetWaterLabel': 'लक्षित जल मात्रा (लीटर) — वैकल्पिक',
    'pumping.override.targetWaterHint': 'अवधि से अनुमान के लिए खाली छोड़ें',
    'pumping.override.durationLabel': 'अवधि सीमा (मिनट) — वैकल्पिक',
    'pumping.override.durationHint': 'इस समय के बाद पंप स्वचालित रूप से बंद हो जाएगा',
    'pumping.override.startNow': 'अभी पंप शुरू करें',
    'pumping.override.stopSave': 'पंप रोकें और सहेजें',
    'pumping.override.saving': 'सत्र सहेजा जा रहा है…',
    'pumping.override.pumpRunning': 'पंप चल रहा है',
    'pumping.override.estWater': 'अनुमानित पानी',
    'pumping.override.estEnergy': 'अनुमानित ऊर्जा',
    'pumping.override.startedAt': 'शुरू हुआ',
    'pumping.override.durationLimitLabel': 'अवधि सीमा',
    // Reports new
    'reports.liveDataTitle': 'रिपोर्ट Supabase से लाइव डेटा लेती हैं',
    'reports.liveDataDesc': 'प्रत्येक PDF आपके डेटाबेस से ताज़ा बनाई जाती है। सुनिश्चित करें कि आप इंटरनेट से जुड़े हैं।',
    'reports.allInOne': 'सब-एक-में',
    'reports.generating': 'बनाया जा रहा है…',
    'reports.downloaded': 'डाउनलोड हो गया!',
    'reports.footer': 'रिपोर्ट PDF प्रारूप में बनाई जाती हैं। सभी डेटा गढ़ेश्वर ग्राम पंचायत का है।',
  },
  mr: {
    // Header
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.solar': 'सौर ऊर्जा',
    'nav.pumping': 'पाणी पंपिंग',
    'nav.grid': 'वीज ग्रिड',
    'nav.reports': 'अहवाल',
    'nav.about': 'माहिती',
    
    // Dashboard
    'dashboard.title': 'डॅशबोर्ड',
    'dashboard.status.safe': 'सौर ऊर्जा सुरक्षित',
    'dashboard.status.caution': 'बॅटरी सावधगिरी',
    'dashboard.status.stop': 'भार थांबवा',
    'dashboard.statusGuide': 'स्थिती मार्गदर्शक',
    'dashboard.statusSafe': 'सौर ऊर्जा सुरक्षित',
    'dashboard.statusCareful': 'बॅटरी सावधपणे वापरा',
    'dashboard.statusStop': 'जड उपकरणे बंद करा',
    'dashboard.outages': 'या महिन्यात वीज खंडित',
    'dashboard.solarHours': 'आज सौर तास',
    'dashboard.waterPumped': 'पंप केलेले पाणी',
    'dashboard.energySaved': 'वाचवलेली ऊर्जा',
    'dashboard.village': 'गढेश्वर गाव',
    'dashboard.location': 'महाराष्ट्र',
    'dashboard.solarForecast': 'आजचा सौर अंदाज',
    'dashboard.waterTank': 'पाणी टाकी भरणे',
    'dashboard.goldenHour': 'पुढील सुवर्ण तास',
    'dashboard.recentAlerts': 'अलीकडील सूचना',
    'dashboard.startPump': 'पंप चालू करा',
    'dashboard.todaySchedule': 'आजचे वेळापत्रक',
    'dashboard.downloadReport': 'अहवाल डाउनलोड करा',
    'dashboard.statusSafe.desc': 'पाणी पंपिंगसाठी अनुकूल परिस्थिती',
    'dashboard.statusCaution.desc': 'मर्यादित सौर ऊर्जा उपलब्ध',
    'dashboard.statusStop.desc': 'ग्रिड विश्वसनीयता कमी, बॅटरी वाचवा',
    'dashboard.peakGeneration': 'शिखर उत्पादन',
    'dashboard.estimatedOutput': 'अंदाजित आउटपुट',
    'dashboard.weather': 'हवामान',
    'dashboard.sunny': 'सूर्यप्रकाश ☀️',
    'dashboard.generationConfidence': 'उत्पादन आत्मविश्वास',
    'dashboard.targetEvening': 'लक्ष्य: संध्याकाळपर्यंत 85%',
    'dashboard.startingIn': 'सुरू होत आहे',
    'dashboard.timeWindow': 'वेळेची खिडकी',
    'dashboard.recommendedAction': 'शिफारस केलेली कृती',
    'dashboard.pumpWater': 'पाणी पंप करा',
    'dashboard.alert.grid': 'उद्या दुपारी 2:00 ते 4:00 दरम्यान वीज खंडित होण्याची शक्यता',
    'dashboard.alert.solar': 'सुवर्ण तास 3 तासांत सुरू होत आहे - पंपिंगची तयारी करा',
    'dashboard.alert.water': 'पाण्याची टाकी 50% भरली आहे - पंपिंग सत्राचे वेळापत्रक करा',
    'dashboard.alert.1hour': '1 तासापूर्वी',
    'dashboard.alert.2hours': '2 तासांपूर्वी',
    'dashboard.alert.4hours': '4 तासांपूर्वी',
    
    // Solar
    'solar.title': 'सौर विश्लेषण',
    'solar.panelEfficiency': 'पॅनेल कार्यक्षमता',
    'solar.dataSource': 'डेटा स्रोत: NASA POWER API',
    'solar.lastUpdated': 'शेवटचे अपडेट',
    'solar.goldenHours': 'सुवर्ण तास (शिखर उत्पादन)',
    'solar.forecast7day': '७-दिवसीय सौर अंदाज',
    'solar.downloadForecast': 'अंदाज डाउनलोड करा',
    
    // Pumping
    'pumping.title': 'पाणी पंपिंग',
    'pumping.liveStatus': 'लाइव्ह पंप स्थिती',
    'pumping.running': 'चालू आहे',
    'pumping.stopped': 'थांबलेले',
    'pumping.voltageSolar': 'व्होल्टेज आणि सौर सहसंबंध',
    'pumping.schedule': 'आजचे वेळापत्रक',
    'pumping.manualOverride': 'मॅन्युअल नियंत्रण',
    'pumping.downloadSchedule': 'वेळापत्रक डाउनलोड करा',
    
    // Grid
    'grid.title': 'ग्रिड विश्लेषण',
    'grid.liveStatus': 'लाइव्ह ग्रिड स्थिती',
    'grid.voltageQuality': 'व्होल्टेज गुणवत्ता',
    'grid.upcomingOutages': 'आगामी खंडित',
    'grid.monthlyReliability': 'मासिक विश्वसनीयता',
    'grid.outageLog': 'खंडित लॉग',
    'grid.alertMe': 'पुढील खंडितापूर्वी मला सूचित करा',
    
    // Reports
    'reports.title': 'अहवाल',
    'reports.dateRange': 'तारीख श्रेणी',
    'reports.reportType': 'अहवाल प्रकार',
    'reports.timeOfDay': 'दिवसाचा वेळ',
    'reports.generate': 'अहवाल तयार करा',
    'reports.download': 'PDF डाउनलोड करा',
    'reports.shareWhatsApp': 'व्हाट्सअॅपद्वारे शेअर करा',
    'reports.history': 'अहवाल इतिहास',
    
    // About
    'about.title': 'सूर्य-संचय बद्दल',
    'about.howItWorks': 'हे कसे कार्य करते',
    'about.step1': 'उपग्रह डेटा',
    'about.step2': 'AI प्रक्रिया',
    'about.step3': 'वेळापत्रक तयार',
    'about.faq': 'वारंवार विचारले जाणारे प्रश्न',
    'about.impact': 'आमचा प्रभाव',
    'about.sdg7': 'SDG ध्येय 7: परवडणारी आणि स्वच्छ ऊर्जा',
    'about.sdg8': 'SDG ध्येय 8: चांगले काम आणि आर्थिक वाढ',
    'about.contact': 'आमच्याशी संपर्क साधा',
    'about.poweredBy': 'उपग्रह डेटा आणि सामुदायिक कृतीद्वारे समर्थित',
    
    // Common
    'common.liters': 'लिटर',
    'common.hours': 'तास',
    'common.minutes': 'मिनिटे',
    'common.today': 'आज',
    'common.tomorrow': 'उद्या',
    'common.thisWeek': 'या आठवड्यात',
    'common.thisMonth': 'या महिन्यात',
    'common.updatedAgo': '२ मिनिटांपूर्वी अपडेट केले',
    
    // Grid
    'grid.subtitle': 'ग्रिड विश्वासार्हतेचे निरीक्षण करा आणि खंडिततेनुसार योजना करा',
    'grid.online': 'ऑनलाइन',
    'grid.offline': 'ऑफलाइन',
    'grid.voltage': 'व्होल्टेज',
    'grid.frequency': 'वारंवारता',
    'grid.monthlyUptime': 'मासिक अपटाइम',
    'grid.outagesThisMonth': 'या महिन्यात आउटेज',
    'grid.stable': 'स्थिर',
    'grid.normal': 'सामान्य',
    'grid.vsLastMonth': 'मागील महिन्याच्या तुलनेत',
    'grid.currentVoltage': 'सध्याचे व्होल्टेज',
    'grid.optimalRange': 'इष्टतम श्रेणी',
    'grid.min': 'किमान',
    'grid.max': 'कमाल',
    'grid.optimal': 'इष्टतम',
    'grid.reason': 'कारण',
    'grid.area': 'क्षेत्र',
    'grid.averageUptime': 'सरासरी अपटाइम',
    'grid.totalOutages': 'एकूण आउटेज',
    'grid.date': 'तारीख',
    'grid.time': 'वेळ',
    'grid.duration': 'कालावधी',
    'grid.scheduledMaintenance': 'नियोजित देखभाल',
    'grid.lineRepair': 'लाइन दुरुस्ती',
    'grid.transformerUpgrade': 'ट्रान्सफॉर्मर अपग्रेड',
    
    // Solar
    'solar.subtitle': 'रिअल-टाइम सौर विश्लेषण आणि अंदाज',
    'solar.optimalPerformance': 'इष्टतम कामगिरी',
    'solar.todaysGeneration': 'आजचे उत्पादन',
    'solar.target': 'लक्ष्य: 8.5 kWh',
    'solar.24hProfile': '24-तास सौर उत्पादन प्रोफाइल',
    'solar.goldenHoursDesc': 'अंबरमध्ये हायलाइट केलेले (11 AM - 2 PM)',
    'solar.goldenHoursTime': 'सुवर्ण तास: 11:00 AM - 2:00 PM',
    'solar.peakWindow': 'पीक जनरेशन विंडो - पाणी पंपिंगसाठी इष्टतम',
    'solar.weather.sunny': 'सूर्यप्रकाश',
    'solar.weather.cloudy': 'ढगाळ',
    'solar.weather.partlyCloudy': 'अंशतः ढगाळ',
    'solar.excellent': 'उत्कृष्ट',
    'solar.good': 'चांगले',
    'solar.fair': 'ठीक',
    'solar.panelDetails': 'सौर पॅनेल तपशील',
    'solar.totalCapacity': 'एकूण क्षमता',
    'solar.panelType': 'पॅनेल प्रकार',
    'solar.installDate': 'स्थापना तारीख',
    'solar.warranty': 'वॉरंटी कालावधी',
    'solar.monthlyPerformance': 'मासिक कामगिरी',
    'solar.avgDaily': 'दैनंदिन सरासरी',
    'solar.bestDay': 'सर्वोत्तम दिवस',
    'solar.activePanels': 'सक्रिय पॅनेल',
    'solar.temperature': 'तापमान',
    'solar.cloudCover': 'ढग आवरण',
    
    // Pumping
    'pumping.subtitle': 'सौर शिखरा दरम्यान पाणी पंपिंग ऑप्टिमाइझ करा',
    'pumping.currentVoltage': 'सध्याचे व्होल्टेज',
    'pumping.solarGeneration': 'सौर उत्पादन',
    'pumping.waterFlow': 'पाण्याचा प्रवाह',
    'pumping.runningDuration': 'चालण्याचा कालावधी',
    'pumping.optimal': 'इष्टतम',
    'pumping.correlationDesc': 'ग्रिड व्होल्टेज आणि सौर उत्पादन दरम्यान सहसंबंध',
    'pumping.voltage': 'व्होल्टेज',
    'pumping.solar': 'सौर',
    'pumping.duration': 'कालावधी',
    'pumping.solarPower': 'सौर ऊर्जा',
    'pumping.waterTarget': 'पाणी लक्ष्य',
    'pumping.status.completed': 'पूर्ण',
    'pumping.status.active': 'सक्रिय',
    'pumping.status.scheduled': 'नियोजित',
    'pumping.override.title': 'मॅन्युअल ओव्हरराइड',
    'pumping.override.desc': 'पंप व्यक्तिचलितपणे नियंत्रित करण्यासाठी स्वयंचलित वेळापत्रक ओव्हरराइड करा.',
    'pumping.override.important': 'महत्वाचे विचार:',
    'pumping.override.rule1': 'सुरू करण्यापूर्वी सध्याचे सौर उत्पादन तपासा',
    'pumping.override.rule2': 'ग्रिड व्होल्टेज स्थिर (220-240V) असल्याची खात्री करा',
    'pumping.override.rule3': 'पाण्याच्या टाकीच्या पातळीचे निरीक्षण करा',
    'pumping.override.rule4': 'मॅन्युअल धावा नियोजित ऑपरेशन्सवर परिणाम करू शकतात',
    'pumping.override.currentCond': 'सध्याची परिस्थिती:',
    'pumping.override.cancel': 'रद्द करा',
    'pumping.override.stop': 'पंप थांबवा',
    'pumping.override.start': 'पंप सुरू करा',
    
    // About
    'about.subtitle': 'शाश्वत शेतीसाठी स्मार्ट सौर व्यवस्थापनासह ग्रामीण भारताचे सक्षमीकरण',
    'about.badge.solar': 'सौर-संचलित',
    'about.badge.ai': 'AI-संचलित',
    'about.badge.gov': 'शासकीय-दर्जा',
    'about.howItWorksSubtitle': 'सौर वापर ऑप्टिमाइझ करण्यासाठी तीन सोप्या पायऱ्या',
    'about.step': 'पायरी',
    'about.impactSubtitle': 'गढेश्वर गावाचे वास्तविक निकाल',
    'about.impact.villages': 'गावे समाविष्ट',
    'about.impact.energy': 'वाचवलेली ऊर्जा',
    'about.impact.water': 'पंप केलेले पाणी',
    'about.impact.cost': 'खर्चात बचत',
    'about.sdgTitle': 'UN शाश्वत विकास उद्दिष्टांमध्ये योगदान',
    'about.sdg7.desc': 'सौर ऊर्जेचा वापर जास्तीत जास्त वाढवून आणि ग्रिडवरचे अवलंबित्व कमी करून, आम्ही सर्वांसाठी परवडणारी, विश्वासार्ह, शाश्वत ऊर्जा नक्की करतो.',
    'about.sdg8.desc': 'ऑपरेटिंग खर्च कमी करणे आणि कृषी उत्पादकता सुधारण्यामुळे शाश्वत आर्थिक वाढीला प्रोत्साहन मिळते आणि शेतकऱ्यांचे जीवनमान सुधारते.',
    'about.faqSubtitle': 'सूर्य-संचय बद्दल सामान्य प्रश्न',
    'about.contactTech': 'तांत्रिक समर्थन',
    'about.contactAdmin': 'प्रशासकीय कार्यालय',
    'about.contactPrivacy': 'डेटा गोपनीयता आणि सुरक्षा',
    'about.contactPrivacyDesc': 'सर्व डेटा सुरक्षितपणे संग्रहित केला जातो आणि भारत सरकारच्या डेटा संरक्षण मार्गदर्शक तत्त्वांचे पालन करतो.',
    'about.btn.contact': 'समर्थनाशी संपर्क साधा',
    'about.btn.docs': 'दस्तऐवज पहा',
    'about.tags.api': 'NASA POWER API',
    'about.tags.ai': 'AI/ML प्रक्रीया',
    'about.tags.monitor': 'रिअल-टाइम मॉनिटरिंग',
    'about.tags.feedback': 'सामुदायिक अभिप्राय',
    'reports.subtitle': 'अधिकृत अनुपालन अहवाल तयार करा आणि डाउनलोड करा',
    'reports.filterTitle': 'अहवाल फिल्टर करा',
    'reports.previewTitle': 'अहवाल पूर्वावलोकन',
    'reports.graphTitle': 'ग्राफिकल सादरीकरण',
    'reports.cat.solar.title': 'सौर कामगिरी अहवाल',
    'reports.cat.solar.desc': 'सौर पॅनेल कार्यक्षमता आणि उत्पादनाचे सविस्तर विश्लेषण',
    'reports.cat.pumping.title': 'पाणी पंपिंग अहवाल',
    'reports.cat.pumping.desc': 'पाण्याचा वापर, पंपिंग वेळापत्रक अनुपालन आणि ऑप्टिमायझेशन',
    'reports.cat.grid.title': 'ग्रिड विश्वासार्हता अहवाल',
    'reports.cat.grid.desc': 'आउटेज पॅटर्न, व्होल्टेज गुणवत्ता आणि ग्रिड कामगिरी',
    'reports.cat.compliance.title': 'अनुपालन अहवाल',
    'reports.cat.compliance.desc': 'सरकारी योजना अनुपालन आणि SDG ध्येय ट्रॅकिंग',
    'reports.cat.combined.title': 'एकत्रित अहवाल',
    'reports.cat.combined.desc': 'सौर, पंपिंग आणि ग्रिड डेटासह सर्व-एकत्रित अहवाल',
    'reports.period': 'कालावधी:',
    'reports.keyMetrics': 'प्रमुख मेट्रिक्स',
    'reports.metric.gen': 'एकूण उत्पादन',
    'reports.metric.peak': 'पीक पॉवर',
    'reports.metric.eff': 'कार्यक्षमता',
    'reports.metric.golden': 'सुवर्ण तास',
    'reports.metric.water': 'एकूण पंप केलेले पाणी',
    'reports.metric.sessions': 'पंपिंग सत्रे',
    'reports.metric.energy': 'वापरलेली ऊर्जा',
    'reports.metric.compliance': 'वेळापत्रक अनुपालन',
    'reports.metric.uptime': 'ग्रिड अपटाइम',
    'reports.metric.outages': 'एकूण आउटेज',
    'reports.metric.avgVolt': 'सरासरी व्होल्टेज',
    'reports.metric.downtime': 'डाउनटाइम तास',
    'reports.metric.sdg7': 'SDG 7 स्कोअर',
    'reports.metric.sdg8': 'SDG 8 स्कोअर',
    'reports.metric.kusum': 'PM-KUSUM अनुपालन',
    'reports.metric.savings': 'खर्च बचत',
    'reports.col.date': 'तयार केलेली तारीख',
    'reports.col.type': 'अहवाल प्रकार',
    'reports.col.period': 'कालावधी',
    'reports.col.size': 'आकार',
    'reports.col.status': 'स्थिती',
    'reports.col.actions': 'कृती',
    'common.action': 'कृती',
    'common.weekly': 'साप्ताहिक',
    'common.monthly': 'मासिक',
    'common.quarterly': 'त्रैमासिक',
    'common.yearly': 'वार्षिक',
    'common.custom': 'सानुकूल तारीख श्रेणी',
    'reports.period.weekly': 'मागील 7 दिवस',
    'reports.period.monthly': 'मागील 30 दिवस',
    'reports.period.quarterly': 'मागील 3 महिने',
    'reports.period.yearly': 'मागील 12 महिने',
    'reports.period.custom': 'सानुकूल श्रेणी',
    'common.startDate': 'सुरुवात तारीख',
    'common.endDate': 'शेवटची तारीख',
    'common.lastMonth': 'मागील महिना',
    // Common UI
    'common.refresh': 'रिफ्रेश करा',
    'common.live': 'लाइव्ह',
    'common.loading': 'लोड होत आहे…',
    'common.noData': 'डेटा आढळला नाही',
    'common.manual': 'मॅन्युअल',
    'common.updated': 'अपडेट केले',
    // Dashboard new
    'dashboard.subtitle': 'गढेश्वर ग्राम पंचायत · सौर देखरेख',
    'dashboard.activePanels': 'सक्रिय पॅनेल',
    'dashboard.moneySaved': 'पैसे वाचवले',
    'dashboard.villageDesc': 'सौर ऊर्जेवर पाणी पंपिंग',
    'dashboard.quickActions': 'त्वरित क्रिया',
    'dashboard.action.pumping': 'पंपिंग सत्रे',
    'dashboard.action.pumpingDesc': 'सर्व पाणी पंपिंग नोंदी पहा',
    'dashboard.action.grid': 'ग्रिड मॉनिटर',
    'dashboard.action.gridDesc': 'लाइव्ह ग्रिड स्थिती तपासा',
    'dashboard.action.reportDesc': 'सौर कार्यप्रदर्शन PDF निर्यात करा',
    // Grid new
    'grid.realtimeDesc': 'रिअल-टाइम ग्रिड स्थिती आणि इतिहास',
    'grid.currentStatus': 'सध्याची स्थिती',
    'grid.uptime': 'अपटाइम',
    'grid.totalRecords': 'एकूण नोंदी',
    'grid.onlineEvents': 'ऑनलाइन घटना',
    'grid.voltageTrend': 'व्होल्टेज ट्रेंड',
    'grid.history': 'ग्रिड इतिहास',
    'grid.status': 'स्थिती',
    'grid.timestamp': 'वेळ',
    'grid.noRecords': 'ग्रिड नोंदी आढळल्या नाहीत',
    // Pumping new
    'pumping.totalSessions': 'एकूण सत्रे',
    'pumping.energyUsed': 'वापरलेली ऊर्जा',
    'pumping.efficiency': 'कार्यक्षमता',
    'pumping.recentSessions': 'अलीकडील सत्रे',
    'pumping.total': 'एकूण',
    'pumping.water': 'पाणी',
    'pumping.energy': 'ऊर्जा',
    'pumping.startTime': 'सुरुवात',
    'pumping.noSessions': 'पंपिंग सत्रे आढळली नाहीत',
    'pumping.override.active': 'ओव्हरराइड सक्रिय',
    'pumping.override.on': 'ओव्हरराइड चालू',
    'pumping.override.off': 'ओव्हरराइड बंद',
    'pumping.override.disabled': 'मॅन्युअल ओव्हरराइड अक्षम आहे',
    'pumping.override.disabledDesc': 'स्वयंचलित वेळापत्रकाबाहेर पंप व्यक्तिचलितपणे चालू/बंद करण्यासाठी ओव्हरराइड सक्षम करा. केवळ आपत्कालीन परिस्थितीत वापरा.',
    'pumping.override.warning': 'इशारा',
    'pumping.override.warningText': 'मॅन्युअल ओव्हरराइड स्वयंचलित सौर वेळापत्रक बायपास करते. केवळ आवश्यक असल्यास वापरा. सत्रे मॅन्युअल म्हणून नोंदवले जातील.',
    'pumping.override.targetWaterLabel': 'लक्ष्य पाण्याचे प्रमाण (लिटर) — पर्यायी',
    'pumping.override.targetWaterHint': 'कालावधीवरून अंदाज करण्यासाठी रिकामे ठेवा',
    'pumping.override.durationLabel': 'कालावधी मर्यादा (मिनिटे) — पर्यायी',
    'pumping.override.durationHint': 'या वेळानंतर पंप स्वयंचलितपणे थांबेल',
    'pumping.override.startNow': 'आता पंप सुरू करा',
    'pumping.override.stopSave': 'पंप थांबवा आणि जतन करा',
    'pumping.override.saving': 'सत्र जतन होत आहे…',
    'pumping.override.pumpRunning': 'पंप चालू आहे',
    'pumping.override.estWater': 'अंदाजित पाणी',
    'pumping.override.estEnergy': 'अंदाजित ऊर्जा',
    'pumping.override.startedAt': 'सुरू झाले',
    'pumping.override.durationLimitLabel': 'कालावधी मर्यादा',
    // Reports new
    'reports.liveDataTitle': 'अहवाल Supabase मधून लाइव्ह डेटा घेतात',
    'reports.liveDataDesc': 'प्रत्येक PDF तुमच्या डेटाबेसमधून नव्याने तयार होतो. इंटरनेटशी जोडलेले असल्याची खात्री करा.',
    'reports.allInOne': 'सर्व-एकत्र',
    'reports.generating': 'तयार होत आहे…',
    'reports.downloaded': 'डाउनलोड झाले!',
    'reports.footer': 'अहवाल PDF स्वरूपात तयार होतात. सर्व डेटा गढेश्वर ग्राम पंचायतचा आहे.',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Initialize language from localStorage or default to 'en'
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('surya-sanchay-language');
      if (savedLanguage === 'en' || savedLanguage === 'hi' || savedLanguage === 'mr') {
        return savedLanguage;
      }
    }
    return 'en';
  });

  // Wrapper function to save language to localStorage when changed
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('surya-sanchay-language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] ?? translations['en'][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}